# Generated by Django 5.2.10 on 2026-01-26 15:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=500, verbose_name='질문')),
                ('ai_response', models.TextField(verbose_name='AI 답변')),
                ('markdown_content', models.TextField(verbose_name='마크다운 내용')),
                ('reference_urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=500), blank=True, default=list, size=None, verbose_name='참고 URL')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None, verbose_name='태그')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '학습 로그',
                'verbose_name_plural': '학습 로그',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='search_lear_created_356966_idx'), models.Index(fields=['query'], name='search_lear_query_9f721e_idx')],
            },
        ),
    ]
