# Generated by Django 5.2.10 on 2026-01-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True, verbose_name='URL')),
                ('title', models.CharField(max_length=300, verbose_name='문서 제목')),
                ('excerpt', models.TextField(verbose_name='핵심 내용 발췌')),
                ('source_type', models.CharField(choices=[('official', '공식 문서'), ('blog', '기술 블로그'), ('stackoverflow', 'Stack Overflow'), ('github', 'GitHub'), ('other', '기타')], default='official', max_length=50, verbose_name='출처 유형')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='수집일')),
            ],
            options={
                'verbose_name': '레퍼런스',
                'verbose_name_plural': '레퍼런스',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='태그명')),
                ('slug', models.SlugField(unique=True, verbose_name='슬러그')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LearningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=500, verbose_name='질문')),
                ('ai_response', models.TextField(verbose_name='AI 답변')),
                ('markdown_content', models.TextField(verbose_name='마크다운 내용')),
                ('is_bookmarked', models.BooleanField(default=False, verbose_name='북마크')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('references', models.ManyToManyField(blank=True, related_name='learning_logs', to='search.reference', verbose_name='참고 문서')),
                ('tags', models.ManyToManyField(blank=True, related_name='learning_logs', to='search.tag', verbose_name='태그')),
            ],
            options={
                'verbose_name': '학습 로그',
                'verbose_name_plural': '학습 로그',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='search_lear_created_356966_idx'), models.Index(fields=['query'], name='search_lear_query_9f721e_idx'), models.Index(fields=['is_bookmarked'], name='search_lear_is_book_8e95e2_idx')],
            },
        ),
    ]
