# Generated by Django 5.2.12 on 2026-03-20 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('generation_compare', '생성→비교'), ('path_trace', '경로추적'), ('retrieval_checkin', '인출 체크인')], max_length=30, verbose_name='유형')),
                ('content', models.JSONField(verbose_name='문제 내용')),
                ('review_interval', models.PositiveIntegerField(default=1, verbose_name='복습 주기(일)')),
                ('next_review_at', models.DateTimeField(blank=True, null=True, verbose_name='다음 복습일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('learning_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='search.learninglog', verbose_name='학습 로그')),
            ],
            options={
                'verbose_name': '연습문제',
                'verbose_name_plural': '연습문제',
                'ordering': ['next_review_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.JSONField(verbose_name='사용자 답변')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='정답 여부')),
                ('ai_feedback', models.TextField(blank=True, verbose_name='AI 피드백')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='점수(0~1)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='시도일')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='search.exercise', verbose_name='연습문제')),
            ],
            options={
                'verbose_name': '풀이 시도',
                'verbose_name_plural': '풀이 시도',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['next_review_at'], name='search_exer_next_re_2c3b76_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['exercise_type'], name='search_exer_exercis_28526e_idx'),
        ),
    ]
