# Generated by Django 5.2.14 on 2026-05-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('generation_compare', '직접 답하기'), ('path_trace', '선택지 고르기'), ('retrieval_checkin', '인출 체크인')], max_length=30, verbose_name='유형'),
        ),
    ]
