# Generated by Django 5.2.14 on 2026-05-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_exercise_exercise_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('generation_compare', '직접 답하기'), ('path_trace', '선택지 고르기')], max_length=30, verbose_name='유형'),
        ),
    ]
