# Generated by Django 5.2.14 on 2026-06-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_alter_exercise_exercise_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='날짜')),
                ('streak_day', models.PositiveIntegerField(default=0, verbose_name='불꽃 n일차')),
                ('question_count', models.PositiveIntegerField(default=0, verbose_name='질문 수')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='연습문제 시도 수')),
                ('pass_count', models.PositiveIntegerField(default=0, verbose_name='통과 수')),
                ('fail_count', models.PositiveIntegerField(default=0, verbose_name='미통과 수')),
                ('summary', models.TextField(blank=True, verbose_name='LLM 요약')),
                ('is_dismissed', models.BooleanField(default=False, verbose_name='팝업 다시보지않기')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '일일 학습일지',
                'verbose_name_plural': '일일 학습일지',
                'ordering': ['-date'],
            },
        ),
    ]
