# Generated by Django 5.2.14 on 2026-06-10 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_dailyjournal'),
    ]

    operations = [
        migrations.AddField(
            model_name='learninglog',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='search.learninglog', verbose_name='부모 질문'),
        ),
    ]
