# Generated by Django 5.2.15 on 2026-06-10 15:33

import pgvector.django.vector
from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_learninglog_parent'),
    ]

    operations = [
        VectorExtension(),  # CREATE EXTENSION IF NOT EXISTS vector (이미 있으면 skip)
        migrations.AddField(
            model_name='learninglog',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True, verbose_name='임베딩'),
        ),
    ]
