# Generated by Django 5.2.15 on 2026-06-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_learninglog_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='learninglog',
            name='answer_source',
            field=models.CharField(blank=True, choices=[('both', '내 기록 + 웹 문서'), ('logs', '내 기록 기반'), ('web', '웹 문서 기반'), ('none', '모델 지식만')], default='', max_length=10, verbose_name='답변 출처'),
        ),
        migrations.AddField(
            model_name='learninglog',
            name='is_truncated',
            field=models.BooleanField(default=False, verbose_name='답변 잘림(max_tokens)'),
        ),
        migrations.AddField(
            model_name='learninglog',
            name='verification',
            field=models.CharField(blank=True, choices=[('pending', '검증 대기'), ('passed', '컨텍스트 일치'), ('suspect', '컨텍스트 불일치 의심')], default='', max_length=10, verbose_name='검증 상태'),
        ),
        migrations.AddField(
            model_name='learninglog',
            name='verification_note',
            field=models.TextField(blank=True, verbose_name='검증 메모'),
        ),
    ]
